Machine: {Balls Per Game: 3, Max extra balls per game: 99, Max extra balls lit: 99,
  Number of tilt warnings: 2, Allow restarts: true, Deadworld Mod Installed: false}
Coil Strength: {flipperLwRMain: 45, flipperLwLMain: 45, flipperUpRMain: 30, flipperUpLMain: 30,
  popperL: 25, popperR: 30, resetDropTarget: 30, knocker: 50, shooterR: 50, shooterL Min: 15,
  shooterL Max: 30, tripDropTarget: 40, trough: 30, slingL: 30, slingR: 30}
Sound: {Initial volume: 5}
Gameplay: {New ball ballsave time: 10, New ball repeating ballsave: false, Multiball ballsave time: 20,
  Block War ballsave time: 15, Time per chain feature: 30, Chain feature difficulty: medium,
  Time for Hurry Up: 10, Block difficulty: medium, Blocks for Ultimate Challenge: 16,
  Mystery ballsave time: 10, Mystery feature add time: 10, Video mode: enemies, Video mode enemies: 15,
  Video mode completion: 100000, Time for Fear shot: 35, Fear ballsave time: 10, Mortis ballsave time: 10,
  Time for Death: 180, Death ballsave time: 20, Time for Death shot: 10, Celebration ballsave time: 20}
Replay: {Replay Type: auto, Replay Percentage: 10, Replay Award: Credit, Replay Levels: 1,
  Replay Level 1: 500000, Replay Level 2: 1000000, Replay Level 3: 1500000, Replay Level 4: 2000000,
  Replay Boost: 200000}
