Machine:
  'Balls Per Game':
    options: [1,10]
    increments: 1
    default: 3
  'Max extra balls per game':
    options: [0,1,2,3,4,5,6,7,8,9,99]
    default: 99
  'Max extra balls lit':
    options: [0,1,2,3,4,5,6,7,8,9,99]
    default: 99
  'Number of tilt warnings':
    options: [0,10]
    increments: 1
    default: 2
  'Allow restarts':
    options: [true, false]
    default: true
  'Deadworld Mod Installed':
    options: [true, false]
    default: false
Coil Strength:
  flipperLwRMain:
    options: [15,60]
    increments: 1
    default: 45
  flipperLwLMain:
    options: [15,60]
    increments: 1
    default: 45
  flipperUpRMain:
    options: [15,60]
    increments: 1
    default: 30
  flipperUpLMain:
    options: [15,60]
    increments: 1
    default: 30
  popperL:
    options: [15,60]
    increments: 1
    default: 25
  popperR:
    options: [15,60]
    increments: 1
    default: 30
  resetDropTarget:
    options: [15,60]
    increments: 1
    default: 30
  knocker:
    options: [15,60]
    increments: 1
    default: 50
  shooterR:
    options: [15,60]
    increments: 1
    default: 50
  shooterL Min:
    options: [15,60]
    increments: 1
    default: 15
  shooterL Max:
    options: [15,60]
    increments: 1
    default: 30
  tripDropTarget:
    options: [15,60]
    increments: 1
    default: 40
  trough:
    options: [15,60]
    increments: 1
    default: 30
  slingL:
    options: [15,60]
    increments: 1
    default: 30
  slingR:
    options: [15,60]
    increments: 1
    default: 30
Sound:
  'Initial volume':
    options: [0,10]
    increments: 1
    default: 5
Gameplay:
  'New ball ballsave time':
    options: [0,20]
    increments: 1
    default: 10
  'New ball repeating ballsave':
    options: [false, true]
    default: false
  'Multiball ballsave time':
    options: [0,30]
    increments: 1
    default: 20
  'Block War ballsave time':
    options: [0,30]
    increments: 1
    default: 15
  'Time per chain feature':
    options: [20,50]
    increments: 5
    default: 30
  'Chain feature difficulty':
    options: ['easy', 'medium', 'hard']
    default: 'medium'
  'Time for Hurry Up':
    options: [5,25]
    increments: 1
    default: 10
  'Block difficulty':
    options: ['easy', 'medium', 'hard']
    default: 'medium'
  'Blocks for Ultimate Challenge':
    options: [8,12,16]
    default: 16
  'Mystery ballsave time':
    options: [5,30]
    increments: 1
    default: 10
  'Mystery feature add time':
    options: [5,30]
    increments: 1
    default: 10
  'Video mode':
    options: ['enemies', 'cows', 'off']
    default: 'enemies'
  'Video mode enemies':
    options: [5,20]
    increments: 1
    default: 15
  'Video mode completion':
    options: [25000,100000]
    increments: 5000
    default: 100000
  'Time for Fear shot':
    options: [10,60]
    increments: 5
    default: 35
  'Fear ballsave time':
    options: [0,30]
    increments: 1
    default: 10
  'Mortis ballsave time':
    options: [0,30]
    increments: 1
    default: 10
  'Time for Death':
    options: [120,240]
    increments: 10
    default: 180
  'Death ballsave time':
    options: [0,30]
    increments: 1
    default: 20
  'Time for Death shot':
    options: [0,30]
    increments: 1
    default: 10
  'Celebration ballsave time':
    options: [0,30]
    increments: 1
    default: 20
Replay:
  'Replay Type':
    options: ['none','auto','fixed','incremental']
    default: 'auto'
  'Replay Percentage':
    options: [5,50]
    increments: 1
    default: 10
  'Replay Award':
    options: ['Credit', 'Extra Ball']
    default: 'Credit'
  'Replay Levels':
    options: [1,2,3,4]
    default: 1
  'Replay Level 1':
    options: [50000,10000000]
    increments: 50000
    default: 500000
  'Replay Level 2':
    options: [50000,10000000]
    increments: 50000
    default: 1000000
  'Replay Level 3':
    options: [50000,10000000]
    increments: 50000
    default: 1500000
  'Replay Level 4':
    options: [50000,10000000]
    increments: 50000
    default: 2000000
  'Replay Boost':
    options: [50000,10000000]
    increments: 50000
    default: 200000
